### PR TITLE
small cleanup code

### PR DESCRIPTION
**Pull request by sergeylanzman**

### CODE REVIEW

**Comment by sergeylanzman** [comment]
Tests fail in master branch too.

**Comment by sergeylanzman** [comment]
@crimsonred 
1. OK I change it
2. It's Does not matter, this call to close with defer or explicitly. ok, I change it.

I start read sdk code because we have a problem with deadlock every 2 weeks. Send to pubnub stopped and we get a lot of goroutines in app. Need restart for fix it. You know the issue about this?

**Comment by crimsonred** [comment]
@sergeylanzman, For the deadlock we would need more details like which PubNub operation is involved and also we need the logs from the SDK when you experience the deadlock. For logging, please check: https://www.pubnub.com/docs/go/pubnub-go-sdk-troubleshooting-guide . When you have the complete info please open a ticket by sending the details to support@pubnub.com.

**Comment by sergeylanzman** [comment]
@crimsonred Your 2 points fixed(reverted)

**Pull request merged**
