### PR TITLE
 satori/go.uuid updated to current version

### PR DESCRIPTION
**Pull request by zhashkevych**
Updated satori/go.uuid to current version

### CODE REVIEW

**Comment by crimsonred** [comment]
@zhashkevych, There are multiple issues with the PR. 

1) The changes will break the initialization of the package for the existing clients. The change could have been handled using the log file for errors.
2) You have added a lock on the PubNub package, pointing to a beta version.
3) A new dependency has been added in the vendor directory, can you let me know the reason?

**Comment by zhashkevych** [comment]
@crimsonred Fixed all mentioned issues. Please do review again.

**Comment by crimsonred** [comment]
@zhashkevych have you manually updated `Gopkg.lock`. There were only four dependencies and yours shows 3 more. Also its pointing to a beta version of PubNub go repo.

And also Travis is build errors due to this.

**Comment by zhashkevych** [comment]
@crimsonred I added Gopkg.lock file to a commit accidentally. Now only Gopkg.toml and utils/strings_utils.go file changes are included to the PR.

**Pull request merged**
