### PR TITLE
Uncomment Pam V3 API code

### PR DESCRIPTION
**Pull request by luna-duclos**
This allows usage of the PAM v3 API

### CODE REVIEW

**Comment by crimsonred** [comment]
Thanks for the PR @luna-duclos. Unfortunately those are not the only changes to make PAMv3 work. When I created these methods the server was not ready to handle these params, specs have changed a bit since then and at this moment I am not sure if these methods would work as it is or not (the unit tests are failing after this change).

The changes to make PAMv3 work with the latest specs are in the backlog. If it is blocking you in some way, please contact support@pubnub.com with the details.

Thanks!

**Comment by luna-duclos** [comment]
> 
> 
> Thanks for the PR @luna-duclos. Unfortunately those are not the only changes to make PAMv3 work. When I created these methods the server was not ready to handle these params, specs have changed a bit since then and at this moment I am not sure if these methods would work as it is or not (the unit tests are failing after this change).
> 
> The changes to make PAMv3 work with the latest specs are in the backlog. If it is blocking you in some way, please contact [support@pubnub.com](mailto:support@pubnub.com) with the details.
> 
> Thanks!

Hey there, I see! 

The unit tests failing is confusing, uncommenting a bunch of functions shouldn't be able to make any tests fail, are you sure the fails are related ?

Either way, I am indeed blocked by this and hoping we can get it working swiftly.

**Comment by luna-duclos** [comment]
Update: I just had a look at the REST api docs and to the best of my ability, the current code should be correct as per the specs I have at least.

**Comment by crimsonred** [comment]
@luna-duclos, there are some other related changes for PAMv3 in our backlog, can you please contact support@pubnub.com with the details of what is blocking you, the use case and the urgency?

**Comment by crimsonred** [comment]
PAMv3 was added, please have a look at https://github.com/pubnub/go/releases/tag/v6.0.1

**Pull request closed without merging**
