### PR TITLE
Refactor to new GAE packages

### PR DESCRIPTION
**Pull request by pedromg**
Refactor to new Google App Engine Golang Packages.

https://github.com/golang/appengine/blob/master/README.md#3-update-code-using-deprecated-removed-or-modified-apis

### CODE REVIEW

**Comment by crimsonred** [comment]
@pedromg, thanks for the pull request. This is in review, we will get back to you shortly.

**Comment by crimsonred** [comment]
@pedromg , a new branch (https://github.com/pubnub/go/tree/pt98645266) has been created for this PR. The example for GAE has also been updated in it. 

The current PubNub SDK still works for the current stable version of the appengine SDK (1.9.23). So we are going to keep this in beta and merge this to master when the appengine and appenginevm SDKs are merged.

**Comment by crimsonred** [comment]
The code has been merged to master.

**Comment by pubnubcraig** [comment]
What does the new GAE packages bring in terms of new features? Anything
worth knowing?

**Comment by crimsonred** [comment]
It has support for Managed VMs on google cloud:

https://cloud.google.com/appengine/docs/managed-vms/

**Pull request closed without merging**
