### PR TITLE
add custom message type

### PR DESCRIPTION
**Pull request by Xavrax**
feat: add `CustomMessageType` to messages and files

add `CustomMessageType` to messages and files

### CODE REVIEW

**Comment by Xavrax** [comment]
I will fix paddings within next PRs with reformating the whole repo.

**Review by seba-aln — APPROVED** [review]
Note to add a ticket for reformat and linting in validation

**Review by seba-aln — APPROVED** [review]
🍏

**Comment by Xavrax** [comment]
@pubnub-release-bot release

**Pull request merged**
